/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StokForm;
import METODS.UrunEkleSilGuncelle;
import StokForm.StokTakipForm;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;

/**
 *
 * @author DELL
 */
public class UrunListesiUpdate extends javax.swing.JFrame {

    /**
     * Creates new form UrunListesi
     */
    public UrunListesiUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDB2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtUpAD = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUpACIKLAMA = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtUpALIS = new javax.swing.JTextField();
        txtUpMIKTAR = new javax.swing.JTextField();
        txtUpSATIS = new javax.swing.JTextField();
        comboUpBIRIM = new javax.swing.JComboBox<>();
        txtUpMARKA = new javax.swing.JTextField();
        comboUpKATEGORI = new javax.swing.JComboBox<>();
        btnGUNCELLE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bulunan Ürün");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tableDB2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tableDB2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ÜRÜN ID", "ÜRÜN ADI", "AÇIKLAMA", "MARKA", "KATEGORİ", "BİRİM", "MİKTAR", "ALIŞ FİYATI", "SATIŞ FİYATI", "KAYIT TARİHİ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDB2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableDB2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableDB2FocusGained(evt);
            }
        });
        tableDB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDB2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDB2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ürün Bilgileri"));
        jPanel5.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("ÜRÜN ADI:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("MARKA:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("KATEGORİ:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("AÇIKLAMA");

        txtUpAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpADActionPerformed(evt);
            }
        });

        txtUpACIKLAMA.setColumns(20);
        txtUpACIKLAMA.setRows(5);
        jScrollPane2.setViewportView(txtUpACIKLAMA);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setText("ALIŞ FİYATI:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setText("BİRİM:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setText("MİKTAR:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("SATIŞ FİYATI:");

        comboUpBIRIM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz...", "PAKET", "ADET", "KOLİ" }));

        comboUpKATEGORI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz...", "BİLGİSAYAR / TABLET", "YAZICILAR / PROJEKSİYON", "TELEFON / TELEFON AKSESUAR", "TV / GÖRÜNTÜ / SES SİSTEMLERİ", "BEYAZ EŞYA", "ELEKTRİKLİ EV ALETLERİ", "FOTO / KAMERA", "KLİMA VE ISITICILAR", "OYUN / OYUN KONSOLLARI", "OYUNCU AKSESUAR" }));
        comboUpKATEGORI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUpKATEGORIActionPerformed(evt);
            }
        });

        btnGUNCELLE.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnGUNCELLE.setText("ÜRÜNÜ GÜNCELLE");
        btnGUNCELLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGUNCELLEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUpMIKTAR, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                    .addComponent(txtUpAD))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel10))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUpMARKA, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtUpALIS)))
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel11))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUpSATIS)
                            .addComponent(comboUpKATEGORI, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(comboUpBIRIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(btnGUNCELLE, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUpAD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUpMARKA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUpMIKTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUpALIS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboUpKATEGORI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUpSATIS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboUpBIRIM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnGUNCELLE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableDB2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableDB2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDB2FocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        tableDB2.setRowHeight(30);
        tableDB2.getColumnModel().getColumn(0).setPreferredWidth(70);
        tableDB2.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableDB2.getColumnModel().getColumn(2).setPreferredWidth(250);
        tableDB2.getColumnModel().getColumn(3).setPreferredWidth(100);
        tableDB2.getColumnModel().getColumn(4).setPreferredWidth(150);
        tableDB2.getColumnModel().getColumn(5).setPreferredWidth(60);
        tableDB2.getColumnModel().getColumn(6).setPreferredWidth(60);
        tableDB2.getColumnModel().getColumn(7).setPreferredWidth(100);
        tableDB2.getColumnModel().getColumn(8).setPreferredWidth(100);
        tableDB2.getColumnModel().getColumn(9).setPreferredWidth(100);
        for(int i=0;i<10;i++){
            tableDB2.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }   
    }//GEN-LAST:event_formWindowOpened

    private void tableDB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDB2MouseClicked
        int index = tableDB2.getSelectedRow();
        TableModel model = tableDB2.getModel();
        //String ID = model.getValueAt(index, 0).toString();
        String AD = model.getValueAt(index, 1).toString();
        String ACIKLAMA = model.getValueAt(index, 2).toString();
        String MARKA = model.getValueAt(index, 3).toString();
        String KATEGORI = model.getValueAt(index, 4).toString();
        String BIRIM = model.getValueAt(index, 5).toString();
        String MIKTAR = model.getValueAt(index, 6).toString();
        String FIYAT_ALIS = model.getValueAt(index, 7).toString();
        String FIYAT_SATIS = model.getValueAt(index, 8).toString();
        
        
        txtUpAD.setText(AD);
        txtUpACIKLAMA.setText(ACIKLAMA);
        txtUpMARKA.setText(MARKA);
        comboUpKATEGORI.setSelectedItem(KATEGORI);
        comboUpBIRIM.setSelectedItem(BIRIM);
        txtUpMIKTAR.setText(MIKTAR);
        txtUpALIS.setText(FIYAT_ALIS);
        txtUpSATIS.setText(FIYAT_SATIS);
    }//GEN-LAST:event_tableDB2MouseClicked

    private void btnGUNCELLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGUNCELLEActionPerformed
        //SEÇİLİ ÜRÜNÜN ID DEĞERİNİ ALIR
        int index2 = tableDB2.getSelectedRow();
        TableModel model = tableDB2.getModel();
        String ID = model.getValueAt(index2, 0).toString();
        System.out.println("ID: " + ID);
        
        //FORM ÜZERİNDEKİ INPUTLARDAN VERILER DEGISKENLERE AKTARILIYOR
        String AD,ACIKLAMA,BIRIM,MARKA,KATEGORI;
        int FIYATALIS,MIKTAR,FIYATSATIS;
        
        AD = txtUpAD.getText().toUpperCase();
        ACIKLAMA = txtUpACIKLAMA.getText().toUpperCase();
        BIRIM = (String)comboUpBIRIM.getSelectedItem();
        MARKA = txtUpMARKA.getText().toUpperCase();
        KATEGORI = (String)comboUpKATEGORI.getSelectedItem();
        MIKTAR = Integer.parseInt(txtUpMIKTAR.getText());
        FIYATALIS=Integer.parseInt(txtUpALIS.getText());
        FIYATSATIS=Integer.parseInt(txtUpSATIS.getText());
        
        //COMBOBOX SEÇİM YAPMAYA ZORLUYOR
        if(KATEGORI!="Seçiniz..." && BIRIM!="Seçiniz..."){           
            //URUN EKLEMEK İÇİN SINIFTAN NESE ÜRETİLİYOR
            UrunEkleSilGuncelle guncelle = new UrunEkleSilGuncelle();
        
            //PRIVATE DEĞİŞKENLERE SET METODLARI İLE ERİŞİM SAĞLANARAK ATAMA YAPILIYOR
            guncelle.setAD(AD);
            guncelle.setACIKLAMA(ACIKLAMA);
            guncelle.setMARKA(MARKA);
            guncelle.setKATEGORI(KATEGORI);
            guncelle.setBIRIM(BIRIM);
            guncelle.setMIKTAR(MIKTAR);
            guncelle.setALIS_FIYATI(FIYATALIS);
            guncelle.setSATIS_FIYATI(FIYATSATIS);
            //EKLEME METODU ÇAĞIRILIYOR
            guncelle.UrunGuncelle(ID);
        }
        else if(KATEGORI=="Seçiniz...")
            JOptionPane.showMessageDialog(null,"Kategori Seçiniz!"); 
        else if(BIRIM=="Seçiniz...")
                JOptionPane.showMessageDialog(null,"Birim Seçiniz!");
    }//GEN-LAST:event_btnGUNCELLEActionPerformed

    private void comboUpKATEGORIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUpKATEGORIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUpKATEGORIActionPerformed

    private void txtUpADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpADActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrunListesiUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrunListesiUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrunListesiUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrunListesiUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrunListesiUpdate().setVisible(true);
            }
        });

        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGUNCELLE;
    public javax.swing.JComboBox<String> comboUpBIRIM;
    public javax.swing.JComboBox<String> comboUpKATEGORI;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tableDB2;
    public javax.swing.JTextArea txtUpACIKLAMA;
    public javax.swing.JTextField txtUpAD;
    public javax.swing.JTextField txtUpALIS;
    public javax.swing.JTextField txtUpMARKA;
    public javax.swing.JTextField txtUpMIKTAR;
    public javax.swing.JTextField txtUpSATIS;
    // End of variables declaration//GEN-END:variables
}
